### ISSUE TITLE
im getting this when i start the bot do you know how i could fix this?

### ISSUE THREAD

**Issue by Dontbesotoxic** [HardwareLounge/gallium-v2#10]
05:21:12.523 [main] INFO  Gallium - Starting JDA...

05:21:16.423 [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.internal.requests.WebSocketClient - Encountered IDENTIFY Rate Limit!

05:21:16.423 [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.internal.requests.WebSocketClient - Encountered IDENTIFY Rate Limit!

05:21:16.423 [JDA MainWS-ReadThread] WARN  net.dv8tion.jda.internal.requests.WebSocketClient - Got disconnected from WebSocket (Code 1000). Appending to reconnect queue

05:21:16.423 [JDA MainWS-ReadThread] WARN  net.dv8tion.jda.internal.requests.WebSocketClient - Got disconnected from WebSocket (Code 1000). Appending to reconnect queue

05:21:24.026 [main] INFO  Gallium - Logged in as Serverbot#9271

05:21:24.028 [main] ERROR Gallium - Error while initializing bot

 java.lang.NullPointerException: Cannot invoke "net.hardwarelounge.gallium.config.RoleSubconfig.getDiscordRoleId()" because the return value of "java.util.Map.get(Object)" is null

at net.hardwarelounge.gallium.command.PunishmentCommands$RolePunishmentCommand.<init>(PunishmentCommands.java:42) ~[build.jar:?]

at net.hardwarelounge.gallium.command.PunishmentCommands$WarnCommand.<init>(PunishmentCommands.java:48) ~[build.jar:?]

at net.hardwarelounge.gallium.listener.SlashCommandListener.<init>(SlashCommandListener.java:54) ~[build.jar:?]

at net.hardwarelounge.gallium.DiscordBot.initializeEventListeners(DiscordBot.java:82) ~[build.jar:?]

at net.hardwarelounge.gallium.DiscordBot.start(DiscordBot.java:66) ~[build.jar:?]

at net.hardwarelounge.gallium.Gallium.main(Gallium.java:60) [build.jar:?]

05:21:24.034 [Thread-0] INFO  Gallium - Shutting down Gallium...

05:21:25.110 [main] INFO  Gallium - Loading configuration config.yml, mapped by net.hardwarelounge.gallium.config.GalliumConfig

05:21:25.167 [main] WARN  Gallium - Config file config.yml is still the default config and might need to be configured!

05:21:25.167 [main] INFO  Gallium - Loading configuration permissions.yml, mapped by net.hardwarelounge.gallium.config.PermissionConfig

05:21:25.180 [main] WARN  Gallium - Config file permissions.yml is still the default config and might need to be configured!

05:21:25.180 [main] INFO  Gallium - Loading configuration security.yml, mapped by net.hardwarelounge.gallium.config.SecurityConfig

05:21:25.186 [main] WARN  Gallium - Config file security.yml is still the default config and might need to be configured!

05:21:25.188 [main] INFO  Gallium - Starting JDA...

05:21:28.881 [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.internal.requests.WebSocketClient - Encountered IDENTIFY Rate Limit!

05:21:28.881 [JDA MainWS-ReadThread] ERROR net.dv8tion.jda.internal.requests.WebSocketClient - Encountered IDENTIFY Rate Limit!

05:21:28.881 [JDA MainWS-ReadThread] WARN  net.dv8tion.jda.internal.requests.WebSocketClient - Got disconnected from WebSocket (Code 1000). Appending to reconnect queue

05:21:28.881 [JDA MainWS-ReadThread] WARN  net.dv8tion.jda.internal.requests.WebSocketClient - Got disconnected from WebSocket (Code 1000). Appending to reconnect queue

05:21:30.141 [Thread-0] INFO  Gallium - Shutting down Gallium...

05:21:31.369 [main] INFO  Gallium - Loading configuration config.yml, mapped by net.hardwarelounge.gallium.config.GalliumConfig

05:21:31.423 [main] WARN  Gallium - Config file config.yml is still the default config and might need to be configured!

05:21:31.423 [main] INFO  Gallium - Loading configuration permissions.yml, mapped by net.hardwarelounge.gallium.config.PermissionConfig

05:21:31.436 [main] WARN  Gallium - Config file permissions.yml is still the default config and might need to be configured!

05:21:31.436 [main] INFO  Gallium - Loading configuration security.yml, mapped by net.hardwarelounge.gallium.config.SecurityConfig

05:21:31.442 [main] WARN  Gallium - Config file security.yml is still the default config and might need to be configured!

05:21:31.443 [main] INFO  Gallium - Starting JDA...

05:21:32.366 [main] INFO  Gallium - Logged in as Serverbot#9271

05:21:32.367 [main] ERROR Gallium - Error while initializing bot

 java.lang.NullPointerException: Cannot invoke "net.hardwarelounge.gallium.config.RoleSubconfig.getDiscordRoleId()" because the return value of "java.util.Map.get(Object)" is null

at net.hardwarelounge.gallium.command.PunishmentCommands$RolePunishmentCommand.<init>(PunishmentCommands.java:42) ~[build.jar:?]

at net.hardwarelounge.gallium.command.PunishmentCommands$WarnCommand.<init>(PunishmentCommands.java:48) ~[build.jar:?]

at net.hardwarelounge.gallium.listener.SlashCommandListener.<init>(SlashCommandListener.java:54) ~[build.jar:?]

at net.hardwarelounge.gallium.DiscordBot.initializeEventListeners(DiscordBot.java:82) ~[build.jar:?]

at net.hardwarelounge.gallium.DiscordBot.start(DiscordBot.java:66) ~[build.jar:?]

at net.hardwarelounge.gallium.Gallium.main(Gallium.java:60) [build.jar:?]

05:21:32.369 [Thread-0] INFO  Gallium - Shutting down Gallium...

![image](https://user-images.githubusercontent.com/63920289/148632593-7d188ba1-2f5b-409d-82ef-3e73b0e60d20.png)

**Comment by DeveloperTK** [comment]
Hey @Dontbesotoxic thank you for trying out my bot. You get the following warnings in the console:
```
05:21:31.423 [main] WARN Gallium - Config file config.yml is still the default config and might need to be configured!

05:21:31.436 [main] WARN Gallium - Config file permissions.yml is still the default config and might need to be configured!

05:21:31.442 [main] WARN Gallium - Config file security.yml is still the default config and might need to be configured!
```
The bot needs a valid config in order to run correctly. There is no documentation on the configuration files, but the fields for the most part are pretty much self explanatory. Just go ahead and change `config.yml` and `permissions.yml`. If you have any questions regarding the configuration, feel free to ask.

**Comment by Dontbesotoxic** [comment]
> 

When i compile the jar should it have config.yml and permissions.yml because its only when i run it via the Docker Desktop App it creates them, and it dose not allow me to edit them for some reason Could you give me any advice on this?

**Comment by DeveloperTK** [comment]
When you start the bot in docker, the config files can be found inside the `/data` volume. You will need to map this to a folder on your disk or create a persistent volume, otherwise the configuration cannot be saved properly
